### Makefile --- 
## 
## Filename     : Makefile
## Description  : Makefile for the SC16IS750 tool.
## Author       : Christophe Burki
## Maintainer   : Christophe Burki
## Created      : Thu Jul 17 17:09:25 2014
## Version      : 1.0.0
## Last-Updated : Fri Jul 18 13:03:38 2014 (7200 CEST)
##           By : Christophe Burki
##     Update # : 4
## URL          : 
## Keywords     : 
## Compatibility: 
## 
######################################################################
## 
### Commentary   : 
## 
## 
## 
######################################################################
## 
### Change log:
## 
## 
######################################################################
## 
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License version 3 as
## published by the Free Software Foundation.
## 
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program; see the file LICENSE.  If not, write to the
## Free Software Foundation, Inc., 51 Franklin Street, Fifth
## ;; Floor, Boston, MA 02110-1301, USA.TARGET := gnublin-sc16is750

## 
######################################################################
## 
### Code         :

TARGET := gnublin-sc16is750
SOURCES := gnublin-sc16is750.cpp

include ../Config.mk
include $(GNUBLINMKDIR)/gnublin.mk

CPPFLAGS += -I../../gnublin-modules/module_sc16is750
OBJECTS += ../../gnublin-modules/module_sc16is750/module_sc16is750.o

######################################################################
### Makefile ends here
